# [[rulesets]]
# group = "[groupname]"
# ruleset = "URL"
# type = "surge-ruleset"
# interval = 86400
#
# supported type: surge-ruleset, quantumultx, clash-domain, clash-ipcidr, clash-classic
# default type: surge-ruleset

# å…¨é‡å¹¿å‘Šæ‹¦æˆª 
# è‡ªå¸¦pri&hjk&è§„åˆ™ä¿®æ­£
[[rulesets]]
group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
ruleset = "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
ruleset = "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising_Domain.yaml"
type = "clash-domain"
