# [[rulesets]]
# group = "[groupname]"
# ruleset = "URL"
# type = "surge-ruleset"
# interval = 86400
#
# supported type: surge-ruleset, quantumultx, clash-domain, clash-ipcidr, clash-classic
# default type: surge-ruleset

# ç»•è¿‡å±€åŸŸç½‘
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml"
type = "clash-classic"

# ç»•è¿‡ Tailscale ç›¸å…³
# [[rulesets]]
# group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
# ruleset = "https://cdn.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Tailscale_OfficialDERP.yaml"
# type = "clash-classic"

[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Tailscale_OfficialDERP_IP.yaml"
type = "clash-ipcidr"

[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Tailscale_OfficialDERP_Domain.yaml"
type = "clash-domain"

[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Tailscale.yaml"
type = "clash-classic"

# ç»•è¿‡ BT ä¸Žä¸‹è½½å™¨
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml"
type = "clash-classic"

# ç»•è¿‡ PT
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml"
type = "clash-classic"

# è‡ªå®šä¹‰ç›´è¿žè§„åˆ™
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Direct.yml"
type = "clash-classic"