# [[rulesets]]
# group = "[groupname]"
# ruleset = "URL"
# type = "surge-ruleset"
# interval = 86400
#
# supported type: surge-ruleset, quantumultx, clash-domain, clash-ipcidr, clash-classic
# default type: surge-ruleset

# éšç§ä¿æŠ¤ (å¹¿å‘Šæ‹¦æˆªå·²åŒ…å«)
[[rulesets]]
group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
ruleset = "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml"
type = "clash-classic"

# ååŠ«æŒ (å¹¿å‘Šæ‹¦æˆªå·²åŒ…å«)
[[rulesets]]
group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
ruleset = "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Hijacking/Hijacking.yaml"
type = "clash-classic"
